###########################################
# makefile for shell program
###########################################
# this file was generated by ai (chatgpt)
# to use with other CPP projects change
# EXECUTABLE= and SOURCE=
###########################################
CC=g++
CFLAGS=-c -Wall #-Wall = all, warnings -c = ???
LDFLAGS=
SOURCES=shell_driver.cpp
OBJECTS=$(SOURCES:.cpp=.o)
EXECUTABLE=shell.bin

all: $(SOURCES) $(EXECUTABLE)

$(EXECUTABLE): $(OBJECTS)
	$(CC) $(LDFLAGS) $(OBJECTS) -o $@

.cpp.o:
	$(CC) $(CFLAGS) $< -o $@

clean:
	rm -f $(OBJECTS) $(EXECUTABLE)
